apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- map1.yaml
- map2.yaml

images:
- name: ivostoy/store
  newName: ivostoy/store
  newTag: 0.12.5.1-f8d26e4
