kind: Service
apiVersion: v1
metadata:
  name: store
  labels:
    app: store
spec:
  type: ClusterIP
  selector:
    app: store
  ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: grpc-api
    - name: rest
      port: 8080
      protocol: TCP
      targetPort: 8080
