grpcAddr: "192.168.99.100:30506"
restAddr: "192.168.99.100:30506"

# secure 0=no TLS, 1=server, 2=mTLS
secure: 0

# generated cert is for localhost

keyFile: "../ssl/server.pem"
certFile: "../ssl/server.crt"
