apiVersion: skaffold/v1
kind: Config
metadata:
  name: mygreet
build:
  artifacts:
  - image: ivostoy/mygreet
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/map1.yaml
    - k8s/map2.yaml
    - k8s/service.yaml
