app:
  message: Hello

server:
  port: 8080

spring:
  main:
    banner-mode: "off"
  datasource:
      platform: h2
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
#      ddl-auto: create-drop

logging:
  level:
    org:
      springframework: ERROR
