app:
  message: Hello

server:
  port: 8080

spring:
  main:
    banner-mode: "off"
    ######################################
    # The bean 'cityRepository', defined in com.example.demo.repository.CityRepository defined in @EnableJpaRepositories
    # declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration, could not be registered.
    # A bean with that name has already been defined in com.example.demo2.model.CityRepository defined in
    # @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration
    # and overriding is disabled.
    #allow-bean-definition-overriding: true
    ######################################
    #allow-bean-definition-overriding: false
  datasource:
      platform: h2
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
#      ddl-auto: create-drop

logging:
  level:
    org:
      springframework: ERROR
