FROM golang:1.13-alpine3.10 as foundation

WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download

FROM foundation as builder

COPY . .

RUN go build -ldflags='-w -s -extldflags "-static"' -o bin/app main.go

FROM gcr.io/distroless/base as runtime

COPY --from=builder /build/bin/app /bin/app

ENTRYPOINT ["/bin/app"]