apiVersion: apps/v1
kind: Deployment
metadata:
  name: boss_pod_template
  labels:
    app: boss_pod_template
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: boss_pod_template
    spec:
      containers:
      - name: boss_pod_template
        image: braincorp/boss_pod_template:latest
        imagePullPolicy: always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        command:
        - ./podinfo
        - --port=8080
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: blue
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:8080/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:8080/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
