apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- map1.yaml
- map2.yaml

images:
- name: ivostoy/hello
  newName: ivostoy/hello
  newTag: 0.11.29.0
- name: ivostoy/mygreet
  newName: ivostoy/mygreet
  newTag: 0.12.2.1
