apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- map1.yaml
- map2.yaml

images:
- name: ivostoy/myvault
  newName: ivostoy/myvault
  newTag: 0.12.4.5-65e91f9-dirty
