// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myvault/myvault.proto

package myvault

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthResponse struct {
	Status               string   `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Time                 string   `protobuf:"bytes,20,opt,name=time,proto3" json:"time,omitempty"`
	Name                 string   `protobuf:"bytes,30,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,40,opt,name=address,proto3" json:"address,omitempty"`
	Version              string   `protobuf:"bytes,50,opt,name=version,proto3" json:"version,omitempty"`
	Build                string   `protobuf:"bytes,60,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_577c758edadb1d88, []int{0}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HealthResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *HealthResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HealthResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *HealthResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *HealthResponse) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthResponse)(nil), "myvault.HealthResponse")
}

func init() { proto.RegisterFile("myvault/myvault.proto", fileDescriptor_577c758edadb1d88) }

var fileDescriptor_577c758edadb1d88 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xa9, 0x68, 0x42, 0x07, 0x51, 0x18, 0x6a, 0x5d, 0xa2, 0x88, 0xf4, 0xd4, 0x53, 0x16,
	0xea, 0xd5, 0xab, 0x20, 0x1e, 0x2b, 0x78, 0xf0, 0xb6, 0x31, 0x63, 0xbb, 0x90, 0xec, 0x86, 0xec,
	0x24, 0xd0, 0xab, 0xaf, 0xe0, 0xcd, 0xd7, 0xf2, 0x15, 0x7c, 0x10, 0xd9, 0x3f, 0x39, 0xf4, 0xb4,
	0xf3, 0xfb, 0xbe, 0x5d, 0xd8, 0xdf, 0xc0, 0x55, 0x7b, 0x18, 0xd5, 0xd0, 0xb0, 0x4c, 0x67, 0xd9,
	0xf5, 0x96, 0x2d, 0xe6, 0x09, 0x8b, 0xdb, 0x9d, 0xb5, 0xbb, 0x86, 0xa4, 0xea, 0xb4, 0x54, 0xc6,
	0x58, 0x56, 0xac, 0xad, 0x71, 0xf1, 0x5a, 0x71, 0x93, 0xda, 0x40, 0xd5, 0xf0, 0x29, 0xa9, 0xed,
	0xf8, 0x10, 0xcb, 0xd5, 0xcf, 0x0c, 0x2e, 0x9e, 0x49, 0x35, 0xbc, 0xdf, 0x92, 0xeb, 0xac, 0x71,
	0x84, 0x4b, 0xc8, 0x1c, 0x2b, 0x1e, 0x9c, 0x80, 0xfb, 0xd9, 0x7a, 0xbe, 0x4d, 0x84, 0x08, 0xa7,
	0xac, 0x5b, 0x12, 0x8b, 0x90, 0x86, 0xd9, 0x67, 0x46, 0xb5, 0x24, 0xee, 0x62, 0xe6, 0x67, 0x14,
	0x90, 0xab, 0xba, 0xee, 0xc9, 0x39, 0xb1, 0x0e, 0xf1, 0x84, 0xbe, 0x19, 0xa9, 0x77, 0xda, 0x1a,
	0xb1, 0x89, 0x4d, 0x42, 0x5c, 0xc0, 0x59, 0x35, 0xe8, 0xa6, 0x16, 0x8f, 0x21, 0x8f, 0xb0, 0x79,
	0x87, 0xf3, 0x37, 0x2f, 0xf8, 0x4a, 0xfd, 0xa8, 0x3f, 0x08, 0x5f, 0x20, 0x8b, 0x7f, 0xc5, 0x65,
	0x19, 0xa5, 0xca, 0x49, 0xaa, 0x7c, 0xf2, 0x52, 0xc5, 0x75, 0x39, 0xad, 0xe8, 0x58, 0x6a, 0x75,
	0xf9, 0xf5, 0xfb, 0xf7, 0x7d, 0x32, 0xc7, 0x5c, 0xee, 0x43, 0x51, 0x65, 0xe1, 0xe5, 0xc3, 0x7f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x9b, 0x26, 0xa0, 0x5c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VaultServiceClient interface {
	Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type vaultServiceClient struct {
	cc *grpc.ClientConn
}

func NewVaultServiceClient(cc *grpc.ClientConn) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/myvault.VaultService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultServiceServer is the server API for VaultService service.
type VaultServiceServer interface {
	Health(context.Context, *empty.Empty) (*HealthResponse, error)
}

// UnimplementedVaultServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVaultServiceServer struct {
}

func (*UnimplementedVaultServiceServer) Health(ctx context.Context, req *empty.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

func RegisterVaultServiceServer(s *grpc.Server, srv VaultServiceServer) {
	s.RegisterService(&_VaultService_serviceDesc, srv)
}

func _VaultService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myvault.VaultService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).Health(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _VaultService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myvault.VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _VaultService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myvault/myvault.proto",
}
