kind: Service
apiVersion: v1
metadata:
  name: hello
  labels:
    app: hello
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: grpc-api
    - name: rest
      port: 8080
      protocol: TCP
      targetPort: 8080
